export const SET_DOGS_INFO = 'SET_DOGS_INFO';
export const SET_DOG_INFO = 'SET_DOG-INFO';
export const SET_FAQ_DATA = 'SET_FAQ_DATA';
export const SET_FAQ_TYPES = 'SET_FAQ_TYPES';
export const SET_FAQ_SUBTYPES = 'SET_FAQ_SUBTYPES';
export const SET_FAQ_SUB_TYPE_CATEGORY = 'SET_FAQ_SUB_TYPE_CATEGORY';  